// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 6.4
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
function ws_blinds(l,k,a){var g=jQuery;var j=g(this);var c=l.parts||3;var h=g("<div>").addClass("ws_effect").css({position:"absolute",width:"100%",height:"100%",left:0,top:0,"z-index":8}).hide().appendTo(a.parent());var d=g("<div>").css({position:"absolute",top:0,left:0,width:"100%",height:"100%",overflow:"hidden"}).appendTo(h);var e=[];for(var f=0;f<c;f++){e[f]=g("<div>").css({position:"absolute",height:"100%",width:(100/c).toFixed(3)+"%",border:"none",margin:0,overflow:"hidden",top:0,left:(100*f/c).toFixed(3)+"%"}).appendTo(h)}function b(p,m,n,i,o){if(l.support.transform&&l.support.transition){if(!m.transform){m.transform=""}if(m.left){m.transform+=" translate3d("+(m.left?m.left:0)+"px,0,0)"}delete m.left;if(n||i){m.transition=n+"ms all "+i+"ms ease-in-out"}p.css(m);if(o){p.on("transitionend webkitTransitionEnd oTransitionEnd MSTransitionEnd",o)}}else{if(n){p.animate(m,n,"swing",o)}else{p.css(m)}}}this.go=function(q,o,w){var n=o>q?1:0;if(w){if(w<=-1){q=(o+1)%k.length;n=0}else{if(w>=1){q=(o-1+k.length)%k.length;n=1}else{return -1}}}h.find("img").stop(true,true);h.show();var t=g(".ws_list",a);if(l.fadeOut){t.fadeOut((1-1/c)*l.duration)}var r=g(k[o]);var s={width:r.width()||l.width,height:r.height()||l.height};var u=r.clone().css(s).appendTo(d);b(u,{left:0});b(u,{left:(!n?1:-1)*u.width()*0.5},l.duration,l.duration*0.1);for(var p=0;p<e.length;p++){var m=e[p];var v=g(k[q]).clone().css({position:"absolute",top:0}).css(s).appendTo(m);b(v,{left:(!n?(-v.width()):(v.width()-m.position().left))});b(v,{left:-m.position().left},(l.duration/(e.length+1))*(n?(e.length-p+1):(p+2)),0,((!n&&p==e.length-1||n&&!p)?function(){j.trigger("effectEnd");h.hide().find("img").remove();u.remove()}:false))}}};// -----------------------------------------------------------------------------------
// http://wowslider.com/
// JavaScript Wow Slider is a free software that helps you easily generate delicious 
// slideshows with gorgeous transition effects, in a few clicks without writing a single line of code.
// Generated by WOW Slider 6.4
//
//***********************************************
// Obfuscated by Javascript Obfuscator
// http://javascript-source.com
//***********************************************
jQuery("#wowslider-container1").wowSlider({effect:"blinds",prev:"",next:"",duration:20*100,delay:20*100,width:1078,height:500,autoPlay:true,autoPlayVideo:false,playPause:false,stopOnHover:true,loop:false,bullets:0,caption:false,captionEffect:"parallax",controls:false,responsive:1,fullScreen:false,onBeforeStep:0,images:0});